name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image and export as tar
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          load: false
          push: false
          tags: app:build
          outputs: type=docker,dest=image.tar

      - name: Copy image tarball
        run: ls -lah . && echo "✓ image.tar built"

      - name: Deploy via Dokku git:load-image
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@195.201.239.228:22/etf-staging"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_push_flags: ""
          # ⚠️ Use Dokku plugin input:
          dokku_git_load_image: "true"
          docker_image_tar: "image.tar"
